### ISSUE TITLE
Broken install using node v6.1.0, npm v3.8.6

### ISSUE THREAD

**Issue by koesbong** [libxmljs/libxmljs#413]
Left this comment on a closed issue, opening a new one, hopefully I could get some help.

Here's the error:

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/orbit/orbit-api/node_modules/libxmljs
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
orbit-api@1.0.0 /opt/orbit/orbit-api
`-- to-iso-string@0.0.2

npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "libxmljs"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.18.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
```

Thank you!

**Comment by koesbong** [comment]
@defunctzombie I am guessing that you closed this because I've seen comments saying that PR #402 fixed this issue, but I am still seeing the issue. Any thoughts what you think I should do?

**Comment by kdecouck** [comment]
I work with OP, we solved the issue by a VM upgrade (in our case to Ubuntu 14.04.4 LTS).

**Comment by grssnbchr** [comment]
I think all of this has nothing to do with node-gyp, libxmljs or whatever, but with gcc. I work on a local 12.04 machine and a remote 14.04 server, and the former uses gcc 4.6.x and the latter 4.8.x. I only had issues on my local machine. After having updated gcc to 4.8.x on my local machine, the problem was solved.

See this SO answer: http://stackoverflow.com/questions/33532528/nodejs-4-5-npm-install-fail-for-bcrypt-and-db-migrate/33532529#33532529

**Comment by YoungElPaso** [comment]
I still have this issue, gcc up-to-date.  

node 6.0.0
npm 4.0.3

**Comment by kadiyalasrividya** [comment]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.8 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.18.8 install script 'node-pre-gyp install --fallback-to-build --loglevel http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\bench\B2B\support-tools\npm-debug.log

Why I'm see this issue
