### ISSUE TITLE
Build Failure on Linux

### ISSUE THREAD

**Issue by phillipw** [libxmljs/libxmljs#456]
Getting the following:

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.39-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/phil/src/swa-dashboard/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/phil/src/swa-dashboard/node_modules/libxmljs/build/Release"
gyp ERR! cwd /home/phil/src/swa-dashboard/node_modules/libxmljs
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/phil/src/swa-dashboard/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/phil/src/swa-dashboard/node_modules/libxmljs/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/phil/src/swa-dashboard/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.39-1-MANJARO
node-pre-gyp ERR! command "/usr/bin/node" "/home/phil/src/swa-dashboard/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/phil/src/swa-dashboard/node_modules/libxmljs
node-pre-gyp ERR! node -v v7.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/phil/src/swa-dashboard/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/phil/src/swa-dashboard/node_modules/libxmljs/build/Release' (1)
npm ERR! Linux 4.4.39-1-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "link"
npm ERR! node v7.3.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.4 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.4 install script 'node-pre-gyp install --fallback-to-build --loglevel http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --loglevel http

**Comment by SpyroZeppeli** [comment]
Got the same issue here, any solution?

**Comment by miguelBarreiro85** [comment]
Same error here!

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.6.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/miguel/mlpbarreiro/excell-to-json/node_modules/libxmljs
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 3.10.0-514.6.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "libxmljs@0.15.0"
npm ERR! node v6.9.5
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.15.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.15.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/miguel/mlpbarreiro/excell-to-json/npm-debug.log

**Comment by phillipw** [comment]
@SpyroZeppeli and @miguelBarreiro85, are you guys also running an arch based distro?

**Comment by rchipka** [comment]
Please run `node-gyp --loglevel=silly rebuild` and post the output

**Comment by flaviusb** [comment]
I get something similar, when I try to `npm install` lime server's node component, which depends on libxmljs:

```
> libxmljs@0.14.3 install /home/currentusername/lime2/aknservices/node_modules/libxmljs
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/jmar150/lime2/aknservices/node_modules/libxmljs
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```
and then finally:

```
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
```

I am on Ubuntu Xenial Xerus.

I had similar problems building on Arch, but I don't have that VM anymore to test this on.

**Comment by flaviusb** [comment]
Could be related to a similar issue with gyp shown here: https://github.com/websockets/ws/issues/458 ?

**Comment by flaviusb** [comment]
After taking the advice in that issue (namely `sudo ln -s /usr/bin/nodejs /usr/bin/node`), `npm install` now works for me.

**Comment by ikokostya** [comment]
Internally `node-gyp` calls `node` command. See https://github.com/npm/npm/issues/9253

**Comment by creatorkuang** [comment]
Got the same issue here, any solution?

**Comment by miguelBarreiro85** [comment]
Solved! remved centOS installed ubuntu 16!|

2017-02-12 16:48 GMT+00:00 Weipeng Kuang <notifications@github.com>:

**Comment by kthkaya** [comment]
Same issue. Ubuntu 14.04 Trusty. sudo ln -s /usr/bin/nodejs /usr/bin/node throws "file already exists".

root@TR-069:/home/user/genieacs/node_modules# npm install libxmljs
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})

> libxmljs@0.18.4 install /home/user/genieacs/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v11-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v11-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v11-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@0.10.37 (node-v11 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v11-linux-x64.tar.gz
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.37"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/user/genieacs/node_modules/libxmljs/.node-gyp"
gyp http GET https://nodejs.org/dist/v0.10.37/node-v0.10.37.tar.gz
gyp http 200 https://nodejs.org/dist/v0.10.37/node-v0.10.37.tar.gz
gyp http GET https://nodejs.org/dist/v0.10.37/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v0.10.37/SHASUMS256.txt
make: Entering directory `/home/user/genieacs/node_modules/libxmljs/build'
make: *** No rule to make target `../.node-gyp/0.10.37/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/home/user/genieacs/node_modules/libxmljs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/home/user/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/user/genieacs/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/user/genieacs/node_modules/libxmljs/build/Release"
gyp ERR! cwd /home/user/genieacs/node_modules/libxmljs
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/user/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/user/genieacs/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/user/genieacs/node_modules/libxmljs/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/genieacs/node_modules/libxmljs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.4.0-31-generic
node-pre-gyp ERR! command "node" "/home/user/genieacs/node_modules/libxmljs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/user/genieacs/node_modules/libxmljs
node-pre-gyp ERR! node -v v0.10.37
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /home/user/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/user/genieacs/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/user/genieacs/node_modules/libxmljs/build/Release' (1)

npm ERR! libxmljs@0.18.4 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.18.4 install script.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "libxmljs"
npm ERR! cwd /home/user/genieacs/node_modules
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
root@TR-069:/home/user/genieacs/node_modules#

**Comment by timdp** [comment]
I ran into this when installing libxmljs from an Amazon Linux instance's startup script.

The common theme here is that the installation runs as root, both in my startup script and in the reported errors above. It all starts here:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/libxmljs/.node-gyp"
```

Then, later, when you get

```
make: *** No rule to make target `../.node-gyp/6.9.5/include/node/common.gypi', needed by `Makefile'.  Stop.
```

presumably, that's because the Makefile expects a certain path, and because gyp fell back to another path, it doesn't exist.

In my case, (manually) installing as a non-privileged user worked fine. Alternatively, as suggested in nodejs/node-gyp#454, you can also add `--unsafe-perm` to `npm i` to allow `gyp` to access the path.

**Comment by timdp** [comment]
Relevant sections from [npm config](https://docs.npmjs.com/misc/config):

> unsafe-perm
> Default: false if running as root, true otherwise
> Type: Boolean
> Set to true to suppress the UID/GID switching when running package scripts. If set explicitly to false, then installing as a non-root user will fail.

> user
> Default: "nobody"
> Type: String or Number
> The UID to set to when running package scripts as root.

**Comment by kthkaya** [comment]
Thanks Tim, in my case it was the node version. i upgraded to 6.9.x and it worked. Now it gives an error about rails :(

**Comment by doomsbuster** [comment]
I have the same issue on the Linux Subsystem for Windows. I have Node V 6.10.2 and NPM v.3.10.10. The Linux subsystem is the Ubuntu 16.04 operating system. Upon closely looking at the logs I figured that it was trying to run `make` command and run `make: cc` and `make: g++`. These were not found on my Linux subsystem and hence it failed to install.

I installed `build-essentials`, `gcc`, `g++` packages and the error went away. `apt-get install build-essentials gcc g++`

**Comment by rchipka** [comment]
Should be fixed in v0.18.5

**Comment by ashishtilara** [comment]
I am seeing similar error with Node8, 

```
Cannot read property 'version' of null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.18.4 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by rchipka** [comment]
Try installing the latest version

**Comment by swapnilhande** [comment]
Still the same error:
`
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/litle-home/shande/.nvm/versions/node/v9.4.0/bin/node',
gyp verb cli   '/usr/local/litle-home/shande/.nvm/versions/node/v9.4.0/bin/node-gyp',
gyp verb cli   '--loglevel=silly',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.4.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.6.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.4.0
gyp verb command install [ '9.4.0' ]
gyp verb install input version string "9.4.0"
gyp verb install installing version: 9.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.4.0
gyp verb build dir attempting to create "build" dir: /usr/local/litle-home/shande/build
gyp verb build dir "build" dir needed to be created? /usr/local/litle-home/shande/build
gyp verb build/config.gypi creating config file
gyp sill build/config.gypi { target_defaults: 
gyp sill build/config.gypi    { cflags: [],
gyp sill build/config.gypi      default_configuration: 'Release',
gyp sill build/config.gypi      defines: [],
gyp sill build/config.gypi      include_dirs: [],
gyp sill build/config.gypi      libraries: [] },
gyp sill build/config.gypi   variables: 
gyp sill build/config.gypi    { asan: 0,
gyp sill build/config.gypi      coverage: false,
gyp sill build/config.gypi      debug_devtools: 'node',
gyp sill build/config.gypi      debug_http2: false,
gyp sill build/config.gypi      debug_nghttp2: false,
gyp sill build/config.gypi      force_dynamic_crt: 0,
gyp sill build/config.gypi      gas_version: '2.23',
gyp sill build/config.gypi      host_arch: 'x64',
gyp sill build/config.gypi      icu_data_file: 'icudt60l.dat',
gyp sill build/config.gypi      icu_data_in: '../../deps/icu-small/source/data/in/icudt60l.dat',
gyp sill build/config.gypi      icu_endianness: 'l',
gyp sill build/config.gypi      icu_gyp_path: 'tools/icu/icu-generic.gyp',
gyp sill build/config.gypi      icu_locales: 'en,root',
gyp sill build/config.gypi      icu_path: 'deps/icu-small',
gyp sill build/config.gypi      icu_small: true,
gyp sill build/config.gypi      icu_ver_major: '60',
gyp sill build/config.gypi      llvm_version: 0,
gyp sill build/config.gypi      node_byteorder: 'little',
gyp sill build/config.gypi      node_enable_d8: false,
gyp sill build/config.gypi      node_enable_v8_vtunejit: false,
gyp sill build/config.gypi      node_install_npm: true,
gyp sill build/config.gypi      node_module_version: 59,
gyp sill build/config.gypi      node_no_browser_globals: false,
gyp sill build/config.gypi      node_prefix: '/',
gyp sill build/config.gypi      node_release_urlbase: 'https://nodejs.org/download/release/',
gyp sill build/config.gypi      node_shared: false,
gyp sill build/config.gypi      node_shared_cares: false,
gyp sill build/config.gypi      node_shared_http_parser: false,
gyp sill build/config.gypi      node_shared_libuv: false,
gyp sill build/config.gypi      node_shared_nghttp2: false,
gyp sill build/config.gypi      node_shared_openssl: false,
gyp sill build/config.gypi      node_shared_zlib: false,
gyp sill build/config.gypi      node_tag: '',
gyp sill build/config.gypi      node_use_bundled_v8: true,
gyp sill build/config.gypi      node_use_dtrace: false,
gyp sill build/config.gypi      node_use_etw: false,
gyp sill build/config.gypi      node_use_lttng: false,
gyp sill build/config.gypi      node_use_openssl: true,
gyp sill build/config.gypi      node_use_perfctr: false,
gyp sill build/config.gypi      node_use_v8_platform: true,
gyp sill build/config.gypi      node_without_node_options: false,
gyp sill build/config.gypi      openssl_fips: '',
gyp sill build/config.gypi      openssl_no_asm: 0,
gyp sill build/config.gypi      shlib_suffix: 'so.59',
gyp sill build/config.gypi      target_arch: 'x64',
gyp sill build/config.gypi      uv_parent_path: '/deps/uv/',
gyp sill build/config.gypi      uv_use_dtrace: false,
gyp sill build/config.gypi      v8_enable_gdbjit: 0,
gyp sill build/config.gypi      v8_enable_i18n_support: 1,
gyp sill build/config.gypi      v8_enable_inspector: 1,
gyp sill build/config.gypi      v8_no_strict_aliasing: 1,
gyp sill build/config.gypi      v8_optimized_debug: 0,
gyp sill build/config.gypi      v8_promise_internal_field_count: 1,
gyp sill build/config.gypi      v8_random_seed: 0,
gyp sill build/config.gypi      v8_trace_maps: 0,
gyp sill build/config.gypi      v8_use_snapshot: true,
gyp sill build/config.gypi      want_separate_host_toolset: 0,
gyp sill build/config.gypi      nodedir: '/usr/local/litle-home/shande/.node-gyp/9.4.0',
gyp sill build/config.gypi      standalone_static_library: 1 } }
gyp verb build/config.gypi writing out config file: /usr/local/litle-home/shande/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/local/litle-home/shande/config.gypi
gyp verb common.gypi checking for gypi file: /usr/local/litle-home/shande/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/litle-home/shande/.nvm/versions/node/v9.4.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/litle-home/shande/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/litle-home/shande/.nvm/versions/node/v9.4.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/litle-home/shande/.node-gyp/9.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/local/litle-home/shande/.node-gyp/9.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/litle-home/shande/.nvm/versions/node/v9.4.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/local/litle-home/shande/.node-gyp/9.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/litle-home/shande',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
'import sitecustomize' failed; use -v for traceback
gyp: binding.gyp not found (cwd: /usr/local/litle-home/shande) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/litle-home/shande/.nvm/versions/node/v9.4.0/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 2.6.32-696.23.1.el6.x86_64
gyp ERR! command "/usr/local/litle-home/shande/.nvm/versions/node/v9.4.0/bin/node" "/usr/local/litle-home/shande/.nvm/versions/node/v9.4.0/bin/node-gyp" "--loglevel=silly" "rebuild"
gyp ERR! cwd /usr/local/litle-home/shande
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
`

**Comment by FrankApiyo** [comment]
I'm still getting this error in 2020. Can someone please help. I have bee stuck for hours now :cry:

**Comment by FrankApiyo** [comment]
I've tried to use nvm to switch between node versions 8, 10 and 12
